moreweb/EdgeBiUI/EdgeBiUI/Controllers/TrackersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Easynet.Edge.UI.Client;
using Easynet.Edge.UI.Data;
using EdgeBiUI.Auxilary;

namespace EdgeBiUI.Controllers
{
    public class TrackersController : Controller
    {
        int acc_id = 0;
        string session_id = null;

        public TrackersController()
        {
            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;
        }

        public ActionResult Index(int account, string session)
        {
            AppState.AccountID = account;
			AppState.SessionID = session;

            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;

            Models.TrackersListModel m = new Models.TrackersListModel();

            using (var client = OltpLogicClient.Open(session_id))
            {
                // Load Channels
                Oltp.ChannelDataTable channels = client.Service.Channel_Get();
                m.Channels = channels.OrderBy(x => x.DisplayName).ToDictionary(c => c.ID, c => c.DisplayName);

                // Load Segments
                Oltp.SegmentDataTable segments = client.Service.Segment_Get(acc_id, true);

                foreach (Oltp.SegmentRow segment in segments)
                {
                    bool is_tracker_segment = ((Auxilary.SegmentAssociationFlags)segment.Association).HasFlag(Auxilary.SegmentAssociationFlags.Gateyway);
                    if (is_tracker_segment)
                    {
                        Oltp.SegmentValueDataTable segment_values = client.Service.SegmentValue_Get(acc_id, segment.SegmentID);
                        m.Segments.Add(new Models.SegmentRowModel() { SegmentRow = segment, Values = segment_values.ToList() });
                    }
                }
            }
            return View(m);
        }

        public PartialViewResult FindTrackers(FormCollection colls)
        {
            List<EdgeBiUI.Models.TrackerRowModel> L = new List<Models.TrackerRowModel>();

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                int? channelID = colls["Channel"] == "0" ? null : (int?)int.Parse(colls["Channel"]);

                int?[] segments = new int?[5];
                
                for(int i=1; i<6; i++)
                {
                    if (colls.AllKeys.Contains("Segment"+i))
                        segments[i-1]=int.Parse(colls["Segment"+i]);
                    else
                        segments[i-1] = null;
                    if (segments[i - 1] == 0)
                        segments[i - 1] = null;
                }

                string Identifier = colls["Identifier"];

                Oltp.GatewayDataTable t;
                if (Identifier.Equals(""))
                    t = client.Service.Gateway_GetGateways(acc_id, channelID, segments);
                else
                    t = client.Service.Gateway_GetByIdentifier(acc_id, Identifier);
                
                Dictionary<int, string> Channels = client.Service.Channel_Get().ToDictionary(c => c.ID, c => c.DisplayName);

                foreach (Oltp.GatewayRow g in t)
                {
                    Models.TrackerRowModel m1 = new Models.TrackerRowModel();
                    m1.TrackerID = g.GK;
                    m1.ChannelName = Channels[g.ChannelID];
                    if (g.IsNameNull())
                        m1.TrackerName = "";
                    else
                        m1.TrackerName = g.Name;
                    m1.Identifier = g.Identifier;

                    L.Add(m1);
                }
            }

            return PartialView("Table", L);
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public PartialViewResult EditTracker(string identifier)
        {
            Models.TrackerModel m = new Models.TrackerModel();

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                m.Tracker = client.Service.Gateway_GetByIdentifier(acc_id, identifier)[0];

                Oltp.SegmentDataTable segments = client.Service.Segment_Get(acc_id, true);
                foreach (Oltp.SegmentRow segment in segments)
                {
                    bool is_tracker_segment = ((Auxilary.SegmentAssociationFlags)segment.Association).HasFlag(Auxilary.SegmentAssociationFlags.Gateyway);
                    if (is_tracker_segment)
                    {
                        Oltp.SegmentValueDataTable segment_values = client.Service.SegmentValue_Get(acc_id, segment.SegmentID);
                        int value;
                        switch (segment.SegmentID)
                        {
                            case 1: value = m.Tracker.Segment1; break;
                            case 2: value = m.Tracker.Segment2; break;
                            case 3: value = m.Tracker.Segment3; break;
                            case 4: value = m.Tracker.Segment4; break;
                            case 5: value = m.Tracker.Segment5; break;
                            default: value = m.Tracker.Segment1; break;
                        }
                        m.Segments.Add(new Models.SegmentRowModel() { SegmentRow = segment, Values = segment_values.ToList(), SelectedValue = value });
                    }
                }
                Oltp.ChannelDataTable channels = client.Service.Channel_Get();
                m.Channels = channels.ToDictionary(c => c.ID, c => c.DisplayName);
                m.LandingPages = client.Service.Page_Get(acc_id, null, true, -1).ToDictionary(p => p.GK, p => p.DisplayName);
                m.AppliedTo = GetReferenceData(m.Tracker, client);
            }


            return PartialView("TrackerDetails", m);

        }

        [HttpPost]
        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult EditTracker(string identifier, FormCollection coll)
        {
            Oltp.GatewayDataTable trackers;
            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                trackers = client.Service.Gateway_GetByIdentifier(acc_id, identifier);

                trackers[0].Name = coll["TrackerName"];
                trackers[0].ChannelID = int.Parse(coll["Channel"]);
                trackers[0].DestinationURL = coll["DestinationURL"];
                trackers[0].PageGK = long.Parse(coll["LandingPage"]);
                foreach (string key in coll.Keys)
                {
                    if (key.Contains("trackerSegmentValue_"))
                    {
                        string segment_id = key.Split('_')[1];
                        int segmentID = int.Parse(segment_id);
                        int segmentValue = int.Parse(coll[key]);
                        switch (segmentID)
                        {
                            case 1: trackers[0].Segment1 = segmentValue; break;
                            case 2: trackers[0].Segment2 = segmentValue; break;
                            case 3: trackers[0].Segment3 = segmentValue; break;
                            case 4: trackers[0].Segment4 = segmentValue; break;
                            case 5: trackers[0].Segment5 = segmentValue; break;
                            default: break;
                        }
                    }
                }

                client.Service.Gateway_Save(trackers);
            }

            return Content("OK");
        }


        private string GetReferenceData(Oltp.GatewayRow tracker, OltpLogicClient client)
        {
            string referenceData = "";
            if (tracker.AdgroupGK < 1)
                return "";

            Oltp.AdgroupDataTable adg = client.Service.Adgroup_GetSingle(tracker.AdgroupGK);
            if (adg.Rows.Count < 1)
                return "";

            Oltp.AdgroupRow adgroup = adg[0];

            Oltp.CampaignDataTable cmpn = client.Service.Campaign_GetSingle(adgroup.CampaignGK);
            if (cmpn.Rows.Count > 0)
                referenceData += "<span>"+(cmpn.Rows[0] as Oltp.CampaignRow).Name + "</span> > ";
            referenceData += "<span>" + adgroup.Name + "</span> > ";

            
            if (!tracker.IsReferenceTypeNull())
            {
                if (tracker.ReferenceType == Oltp.GatewayReferenceType.Creative)
                {
                    Oltp.CreativeDataTable c = client.Service.Creative_GetSingle(tracker.ReferenceID);
                    if (c.Rows.Count > 0)
                        referenceData += "Creative: <span>" + (c[0] as Oltp.CreativeRow).Title + "</span>";
                }
                else
                {
                    Oltp.KeywordDataTable k = client.Service.Keyword_GetSingle(tracker.ReferenceID);
                    if (k.Rows.Count > 0)
                        referenceData += "Keyword: <span>" + (k[0] as Oltp.KeywordRow).Keyword + "</span>";
                }
            }

            return referenceData;
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public PartialViewResult BatchUpdate()
        {
            Models.TrackersBatchModel m = new Models.TrackersBatchModel();

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");


moreweb/EdgeBiUI/EdgeBiUI/Views/Trackers/BatchTrackers.cshtml
@model EdgeBiUI.Models.TrackersBatchModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function BatchUpdate() {
        $.post($('#TrackersEditForm').attr("action"), $('#TrackersEditForm').serialize(), function (data) {
            if (data == "Error")
                window.parent.handleError({ message: "Ranges must be entered in the following format: 111-222,333-444,555,666" });
            else {
                var s = data.split(',');
                window.parent.handleError({ message: s[0] + " trackers were affected (of which " + s[1] + " are new)" });
                //alert(s[0] + " trackers were affected (of which " + s[1] + " are new)");
                closeControllerDialog();
            }
        });
    }
</script>

<div id="container">

    <div class="containerTitle">
       Batch Trackers
    </div>
    @using (Html.BeginForm("BatchUpdate", "Trackers", FormMethod.Post, new { id = "TrackersEditForm" }))
    {
    <div id="Tabs">        
        <ul class="menu">			
			<li class="active" id="General">General</li>
            <li class="ControllerTabsLi" id="Segments">Segments</li>
		</ul>
    </div>

    <div id="TabsContent">
        <div class="General content">
            <div class="segmentRow">
                <div class="segmentRowName">Range</div>
                <div class="segmentRowValue"><input type="text" onkeypress="return handleEnterButton(event);" name="Range" style="width:200px;" /></div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">Channel</div>
                <div class="segmentRowValue">
                    <select name="Channel">
                        <option value="-1">(no change)</option>
                        @foreach (KeyValuePair<int, string> channel in Model.Channels.ToList().OrderBy(s=>s.Value))
                        {
                            <option value="@channel.Key">@channel.Value</option>
                        }
                    </select>
                </div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">Landing Page</div>
                <div class="segmentRowValue">
                    <select name="LandingPage">
                        <option value="-1">(no change)</option>
                        @foreach (KeyValuePair<long, string> landingPage in Model.LandingPages)
                        {
                            <option value="@landingPage.Key">@landingPage.Value</option>
                        }
                    </select>
                </div>
            </div>
        </div>

        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select name="batchtrackersSegmentValue_@(seg.SegmentRow.SegmentID)" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-1">(no change)</option>
						<option value="-1000">Add New...</option>
                        @foreach (Oltp.SegmentValueRow value in seg.Values)
                        {
                            <option value="@(value.ValueID)">@(value.Value)</option>
                        }
                    </select>
                </div>
            </div>
        }
        </div>
      
    </div>


    <div id="Buttons">
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="BatchUpdate();" />
    </div>
        
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Trackers/Index.cshtml
@model EdgeBiUI.Models.TrackersListModel
@using Easynet.Edge.UI.Data;
           
@{
    ViewBag.Title = "Trackers";
}

<script type="text/javascript">

    function openTrackerDetails(identifier) {
        $.get('@(Url.Action("EditTracker", "Trackers"))', { identifier: identifier }, function (data) {
            $('#ControllerDialogDiv').html(data);
            openController(600, 400);
           })
			.fail(window.parent.handleError);
    }

    function openBatchTrackers() {
    	$.get('@(Url.Action("BatchUpdate", "Trackers"))', function (data) {
    		$('#ControllerDialogDiv').html(data);
    		openController(600, 400);
    	})
			.fail(window.parent.handleError);
    }

    function findTrackers() {
        $.post($('#PageEditorForm').attr("action"), $('#PageEditorForm').serialize(), function (data) {
            $("#IndexDynamicTableContainer").html(data);
            $(".IndexTableRowNoResult").css("display", "block");
           })
			.fail(window.parent.handleError);
    }



</script>
    <div style="float:right;">
        <a href="" onclick="openBatchTrackers(); return false;">Batch Update</a>
    </div>
<div class="IndexTopNav" style="clear:both;">

@using (Html.BeginForm("FindTrackers", "Trackers", FormMethod.Post, new { id = "PageEditorForm", defaultbutton = "FilterButton" }))
{
    <div class="FilterSegment">
        <div class="FilterSegmentTitle">
            Channel
        </div>
        <select name="Channel">
            <option value="0">All Channels</option>
            @foreach (KeyValuePair<int, string> channel in Model.Channels.ToList().OrderBy(s=>s.Value))
            {
                <option value="@channel.Key">@channel.Value</option>
            }
        </select>
    </div>

    foreach (EdgeBiUI.Models.SegmentRowModel segment in Model.Segments)
    {
    <div class="FilterSegment">
        <div class="FilterSegmentTitle">
            @segment.SegmentRow.Name
        </div>
        <select name="Segment@(segment.SegmentRow.SegmentID)" style="max-width:110px;">
            <option value="0">(Any)</option>
            <option value="-1">None</option>
            @foreach (Oltp.SegmentValueRow Value in segment.Values)
            {
                <option value="@Value.ValueID">@Value.Value</option>
            }
        </select>
    </div>
    }
    
    <div class="FilterSegment">
        <div class="FilterSegmentTitle">
            Tracker ID
        </div>
        <input type="text" name="Identifier" style="width:100px;" />
    </div>
    
    <input type="button" value="Filter" id="FilterButton" onclick="findTrackers()" style="margin-top:18px;" />
}
</div>

<div id="IndexDynamicTableContainer">
@Html.Partial("Table", Model.Trackers)
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Trackers/Table.cshtml
@model List<EdgeBiUI.Models.TrackerRowModel>
@using Easynet.Edge.UI.Data;

<div class="IndexTable">
    <div class="IndexTableHeader">
        <div class="" style="float:left; width:80%; height:14px; overflow:hidden;"><div style="padding-left:30px;">Name</div></div>
        <div class="" style="float:left; width:20%; height:14px; overflow:hidden;">Channel</div>
    </div>
    @foreach (EdgeBiUI.Models.TrackerRowModel tracker in Model)
    {
        <div class="IndexTableRow" id="IndexTableRow_@(tracker.TrackerID)" onclick="selectRow(@(tracker.TrackerID), false);">
            <div class="IndexTableName" style="width:80%;"><div style="padding-left:30px;" onclick="openTrackerDetails(@tracker.Identifier)" title="Tracker Gk=@tracker.TrackerID">@tracker.TrackerName (@tracker.Identifier)</div></div>
            <div class="IndexTableDesc" style="width:20%;">@tracker.ChannelName</div>
        </div>
    }

    @if (Model.Count == 0)
    {
        <div class="IndexTableRowNoResult">No Trackers Found</div>
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Trackers/TrackerDetails.cshtml
@model EdgeBiUI.Models.TrackerModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function SaveTracker(closeAfter) {
        $.post($('#TrackersEditForm').attr("action"), $('#TrackersEditForm').serialize(), function (data) {
            if (data == "OK") {
                if (closeAfter)
                    closeControllerDialog();
            } else {
                $('#ControllerDialogDiv').html(data);
            }
              }).error(window.parent.handleError);
    }
</script>

<div id="container">

    <div class="containerTitle">
       Editing Tracker @Model.Tracker.Identifier
    </div>
    @using (Html.BeginForm("EditTracker", "Trackers", new { identifier = Model.Tracker.Identifier }, FormMethod.Post, new { id = "TrackersEditForm" }))
    {
    <div id="Tabs">        
        <ul class="menu">			
			<li class="active" id="Details">Details</li>
            <li class="ControllerTabsLi" id="Segments">Segments</li>
		</ul>
    </div>

    <div id="TabsContent">
        <div class="Details content">
            <div class="segmentRow">
                <div class="segmentRowName">Name</div>
                <div class="segmentRowValue"><input type="text"  name="TrackerName" value="@(Model.Tracker.IsNameNull() ? "" : Model.Tracker.Name)" style="width:300px;" /></div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">Destination URL</div>
                <div class="segmentRowValue"><input type="text" name="DestinationURL" value="@(Model.Tracker.IsDestinationURLNull() ? "" : Model.Tracker.DestinationURL)" style="width:300px;" /></div>
            </div>
@*            <div class="segmentRow">
                <div class="segmentRowName">Identifier</div>
                <div class="segmentRowValue"><input type="text" name="Identifier" disabled="disabled" value="@Model.Tracker.Identifier" style="width:150px;" /></div>
            </div>*@
            <div class="segmentRow">
                <div class="segmentRowName">Channel</div>
                <div class="segmentRowValue">
                    <select name="Channel">
                        @foreach (KeyValuePair<int, string> channel in Model.Channels)
                        {
                            <option value="@channel.Key" @(channel.Key==Model.Tracker.ChannelID?"selected='selected'":"")>@channel.Value</option>
                        }
                    </select>
                </div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">Landing Page</div>
                <div class="segmentRowValue">
                    <select name="LandingPage" onchange="handleNewValue(this)" segmentID="999" originalValue="@(Model.Tracker.PageGK)">
                            <option value="-1">(none)</option>
							<option value="-1000">Add New...</option>
                        @foreach (KeyValuePair<long, string> landingPage in Model.LandingPages)
                        {
                            <option value="@landingPage.Key" @(landingPage.Key == Model.Tracker.PageGK ? "selected='selected'" : "")>@landingPage.Value</option>
                        }
                    </select>
                </div>
            </div>

            <div class="segmentRow">
                <div class="segmentRowName">Applied to</div>
                <div class="segmentRowValue appliedTo">@Html.Raw(Model.AppliedTo)</div>
            </div>
        </div>

        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select name="trackerSegmentValue_@(seg.SegmentRow.SegmentID)" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-1">(none)</option>
						<option value="-1000">Add New...</option>
                    @foreach (Oltp.SegmentValueRow value in seg.Values)
                    {
                        <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                    }
                    </select>
                </div>
            </div>
        }
        </div>

        

        
        
    </div>


    <div id="Buttons">
        <input type="button" value="Apply" onclick="SaveTracker(false);" />
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="SaveTracker(true);" />
    </div>
        
    }
</div>