moreweb/EdgeBiUI/EdgeBiUI/Controllers/KeywordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Easynet.Edge.UI.Data;
using Easynet.Edge.UI.Client;
using EdgeBiUI.Auxilary;

namespace EdgeBiUI.Controllers
{
    public class KeywordsController : Controller
    {
        int acc_id = 0;
        string session_id = null;

        public KeywordsController()
        {
            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;
        }

        public ActionResult Index(int account, string session)
        {
            AppState.AccountID = account;
			AppState.SessionID = session;

            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;

            Models.KeywordsListModel m = new Models.KeywordsListModel();
            return View(m);
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public PartialViewResult FindKeywords(string searchText)
        {
            List<Oltp.KeywordRow> L = new List<Oltp.KeywordRow>();
            using (OltpLogicClient client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                string str = searchText.Trim().Length > 0 ? searchText.Trim() + "*" : null;
                Oltp.KeywordDataTable keywords = client.Service.Keyword_Get(acc_id, true, str, true);

                foreach (Oltp.KeywordRow keyword in keywords)
                    L.Add(keyword);
            }

            return PartialView("Table", L);
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult EditKeyword(long keywordGK)
        {
            Models.KeywordModel m = new Models.KeywordModel();

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                m.Keyword = client.Service.Keyword_GetSingle(keywordGK)[0];

                Oltp.AdgroupDataTable keyword_adgroups = client.Service.Adgroup_GetByKeyword(keywordGK);
                Dictionary<int, Oltp.CampaignRow> campaings_dictionaty = client.Service.Campaign_GetIndividualCampaigns(keyword_adgroups.Select(f => f.CampaignGK).ToArray()).ToDictionary(f => f.GK, f => f);

                foreach (Oltp.AdgroupRow r in keyword_adgroups)
                {
                    m.Associations.Add(new Models.AssociationRowModel() { AdGroup = r, Campaign = campaings_dictionaty[(int)r.CampaignGK] });
                }

            }

            return PartialView("~/Views/Keywords/KeywordDetails.cshtml", m);
        }

    }
}

moreweb/EdgeBiUI/EdgeBiUI/Views/Keywords/Index.cshtml
@model EdgeBiUI.Models.KeywordsListModel
@using Easynet.Edge.UI.Data
           
@{
    ViewBag.Title = "Creatives";
}

<script type="text/javascript">

    function openKeywordDetails(keywordGK) {
        $.get('@(Url.Action("EditKeyword", "Keywords"))', { keywordGK: keywordGK }, function (data) {
            $('#ControllerDialogDiv').html(data);
            openController(600, 400);
           })
			.fail(window.parent.handleError);
    }

    function findKeywords() {
        searchText = $("#search_value").val();
        
        $.get('@(Url.Action("FindKeywords", "Keywords"))', { searchText: searchText }, function (data) {
            $('#IndexDynamicTableContainer').html(data);
            $(".IndexTableRowNoResult").css("display", "block");
           })
			.fail(window.parent.handleError);
    }

</script>

<div class="IndexTopNav">
    @using (Html.BeginForm("FindKeywords", "Keywords", FormMethod.Post, new { id = "PageEditorForm", defaultbutton = "FilterButton" }))
    {
        <input type="text" name="search_value" class="searchText" id="search_value" />
        <input type="button" value="Find" id="FilterButton" onclick="findKeywords()" />
    }
</div>

<div id="IndexDynamicTableContainer">
@Html.Partial("Table", Model.Keywords)
</div>


moreweb/EdgeBiUI/EdgeBiUI/Views/Keywords/KeywordDetails.cshtml
@model EdgeBiUI.Models.KeywordModel
@using Easynet.Edge.UI.Data

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });
</script>

<div id="container">

    <div class="containerTitle">
        @Model.Keyword.Keyword
    </div>

    <div id="Tabs">        
        <ul class="menu">
            <li class="ControllerTabsLi active" id="Associations">Associations</li>
		</ul>
    </div>

    <div id="TabsContent">
        
        <div class="Associations content">
        
            <div style="margin-bottom:10px;">Campaigns/Adgroups:</div>

            @foreach (EdgeBiUI.Models.AssociationRowModel association in Model.Associations)
            {
                <div class="associationRow">
                    <span>@(association.Campaign.Name)</span>
                    >
                    <span>@(association.AdGroup.Name)</span>
                </div>
            }
        
        </div>
        
    </div>


    <div id="Buttons">
        <input type="button" value="OK" onclick="closeControllerDialog();" />
    </div>
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Keywords/Table.cshtml
@model List<Oltp.KeywordRow>
@using Easynet.Edge.UI.Data;

<div class="IndexTable">
    <div class="IndexTableHeader">
        <div class="" style="float:left; width:50%; height:14px; overflow:hidden;"><div style="padding-left:30px;">Name</div></div>
    </div>
    @foreach (Oltp.KeywordRow keyword in Model)
    {
        <div class="IndexTableRow" id="IndexTableRow_@(keyword.GK)" onclick="selectRow(@(keyword.GK), false);">
            <div class="IndexTableName"><div style="padding-left:30px;" onclick="openKeywordDetails(@keyword.GK)">@keyword.Keyword</div></div>
        </div>
    }

    @if (Model.Count == 0)
    {
        <div class="IndexTableRowNoResult">No Keywords Found</div>
    }
</div>