moreweb/EdgeBiUI/EdgeBiUI/Controllers/CreativesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Easynet.Edge.UI.Data;
using Easynet.Edge.UI.Client;
using EdgeBiUI.Auxilary;

namespace EdgeBiUI.Controllers
{
    public class CreativesController : Controller
    {
        //int acc_id = 10035;

        int acc_id = 0;
        string session_id = null;

        public CreativesController()
        {
            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;
        }

        public ActionResult Index(int account, string session)
        {
            AppState.AccountID = account;
			AppState.SessionID = session;

            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;

            Models.CreativeListModel m = new Models.CreativeListModel();
            return View(m);
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public PartialViewResult FindCreatives(string searchText)
        {
            Models.CreativeListModel m = new Models.CreativeListModel();

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                Oltp.CreativeDataTable creatives = client.Service.Creative_Get(acc_id, searchText.Trim() + "*", true);

                foreach (Oltp.CreativeRow creative in creatives)
                {
                    if (creative.Title.Trim().Length>0)
                        m.Creatives.Add(creative);
                }                  
            }

            

            return PartialView("Table", m);
        }
        
        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult EditCreative(long creativeGK)
        {
            Models.CreativeModel m = new Models.CreativeModel();

            using (OltpLogicClient client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                Oltp.CreativeRow creative = client.Service.Creative_GetSingle(creativeGK)[0];
                m.Creative = creative;

                Oltp.SegmentDataTable segments = client.Service.Segment_Get(acc_id, false);

                foreach (Oltp.SegmentRow r in segments)
                {
                    bool is_creative_segment = ((Auxilary.SegmentAssociationFlags)r.Association).HasFlag(Auxilary.SegmentAssociationFlags.Creative);
                    if (is_creative_segment)
                    {
                        Oltp.SegmentValueDataTable values = client.Service.SegmentValue_Get(acc_id, r.SegmentID);
                        int value;
                        switch (r.SegmentID)
                        {
                            case 1: value = creative.Segment1; break;
                            case 2: value = creative.Segment2; break;
                            case 3: value = creative.Segment3; break;
                            case 4: value = creative.Segment4; break;
                            case 5: value = creative.Segment5; break;
                            default: value = creative.Segment1; break;
                        }
                        
                        
                        m.Segments.Add(new Models.SegmentRowModel() { SegmentRow = r, Values = values.ToList(), SelectedValue = value });
                    }
                }

                Oltp.AdgroupDataTable creative_adgroups = client.Service.Adgroup_GetByCreative(creativeGK);
                Dictionary<int, Oltp.CampaignRow> campaings_dictionaty = client.Service.Campaign_GetIndividualCampaigns(creative_adgroups.Select(f => f.CampaignGK).ToArray()).ToDictionary(f => f.GK, f => f);

                foreach (Oltp.AdgroupRow r in creative_adgroups)
                {
                    m.Associations.Add(new Models.AssociationRowModel() { AdGroup = r, Campaign = campaings_dictionaty[(int)r.CampaignGK] });
                }

                m.Creative = creative;
                
            }

            return PartialView("~/Views/Creatives/CreativeDetails.cshtml", m);
        }

        [HttpPost]
        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult EditCreative(long creativeGK, FormCollection coll)
        {
            Oltp.CreativeDataTable creatives;
            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");
                creatives = client.Service.Creative_GetSingle(creativeGK);
            }

            foreach (string key in coll.Keys)
            {
                if (key.Contains("creativeSegmentValue_"))
                {
                    string segment_id = key.Split('_')[1];
                    int segmentID = int.Parse(segment_id);
                    int segmentValue = int.Parse(coll[key]);
                    switch (segmentID)
                    {
                        case 1: creatives[0].Segment1 = segmentValue; break;
                        case 2: creatives[0].Segment2 = segmentValue; break;
                        case 3: creatives[0].Segment3 = segmentValue; break;
                        case 4: creatives[0].Segment4 = segmentValue; break;
                        case 5: creatives[0].Segment5 = segmentValue; break;
                        default: break;
                    }
                }
            }
            System.Data.DataTable t = creatives.GetChanges();

            using (var client = OltpLogicClient.Open(session_id))
            {
                client.Service.Creative_Save(creatives);
            }

            return Content("OK");
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult EditMultipleCreatives(string creativesGK)
        {
            List<long> CreativesGK = creativesGK.Split(',').Select(s => s.Length > 0 ? long.Parse(s) : 0).ToList();
            Models.MutliCreativeModel m = new Models.MutliCreativeModel();
            m.CreativesGK = creativesGK;

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                foreach (long creativeGK in CreativesGK)
                {
                    Oltp.CreativeDataTable t = client.Service.Creative_GetSingle(creativeGK);
                    if (t.Count > 0)
                        m.Creatives.Add(t[0]);
                }

                Oltp.SegmentDataTable segments = client.Service.Segment_Get(acc_id, false);

                foreach (Oltp.SegmentRow r in segments)
                {
                    bool is_creative_segment = ((Auxilary.SegmentAssociationFlags)r.Association).HasFlag(Auxilary.SegmentAssociationFlags.Creative);
                    if (is_creative_segment)
                    {
                        Oltp.SegmentValueDataTable values = client.Service.SegmentValue_Get(acc_id, r.SegmentID);
                        int value;
                        switch (r.SegmentID)
                        {
                            case 1: value = GetCommonValue(m.Creatives.Select(x => x.Segment1).ToList()); break;
                            case 2: value = GetCommonValue(m.Creatives.Select(x => x.Segment2).ToList()); break;
                            case 3: value = GetCommonValue(m.Creatives.Select(x => x.Segment3).ToList()); break;
                            case 4: value = GetCommonValue(m.Creatives.Select(x => x.Segment4).ToList()); break;
                            case 5: value = GetCommonValue(m.Creatives.Select(x => x.Segment5).ToList()); break;
                            default: value = GetCommonValue(m.Creatives.Select(x => x.Segment1).ToList()); break;
                        }

                        m.Segments.Add(new Models.SegmentRowModel() { SegmentRow = r, Values = values.ToList(), SelectedValue = value });
                    }
                }
            }

            return PartialView("MultiCreativeDetails", m);
        }

        [HttpPost]
        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult EditMultipleCreatives(string creativesGK, FormCollection coll)
        {
            List<long> CreativesGK = creativesGK.Split(',').Select(s => s.Length > 0 ? long.Parse(s) : 0).ToList();

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                Oltp.CreativeDataTable Creatives = new Oltp.CreativeDataTable();
                foreach (long creativeGK in CreativesGK)
                    Creatives.Merge(client.Service.Creative_GetSingle(creativeGK));

                foreach (string key in coll.Keys)
                {
                    if (key.Contains("creativeSegmentValueEdit_"))
                    {
                        if (coll[key] == "1")
                        {
                            string segment_id = key.Split('_')[1];
                            int segmentID = int.Parse(segment_id);
                            int segmentValue = int.Parse(coll["creativeSegmentValue_" + segment_id]);
                            if (segmentValue != -100)
                            {
                                switch (segmentID)
                                {
                                    case 1: Creatives.ToList().ForEach(x => x.Segment1 = segmentValue); break;

moreweb/EdgeBiUI/EdgeBiUI/Views/Creatives/CreativeDetails.cshtml
@model EdgeBiUI.Models.CreativeModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function SaveCreative(closeAfter) {
        $.post($('#PageEditorForm').attr("action"), $('#PageEditorForm').serialize(), function (data) {
            if (data == "OK") {
                if (closeAfter)
                    closeControllerDialog();
            } else {
                $('#ControllerDialogDiv').html(data);
            }
              }).error(window.parent.handleError);
    }
</script>

<div id="container">

    <div class="containerTitle">
        @Model.Creative.Title
    </div>
    @using (Html.BeginForm("EditCreative", "Creatives", new { creativeGK = Model.Creative.GK }, FormMethod.Post, new { id = "PageEditorForm" }))
    {
    <div id="Tabs">        
        <ul class="menu">
			<li class="active" id="Segments">Segments</li>
			<li class="ControllerTabsLi" id="Details">Details</li>
            <li class="ControllerTabsLi" id="Associations">Associations</li>
		</ul>
    </div>

    <div id="TabsContent">
        
        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select name="creativeSegmentValue_@(seg.SegmentRow.SegmentID)" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-1">(none)</option>
						<option value="-1000">Add New...</option>
                    @foreach (Oltp.SegmentValueRow value in seg.Values)
                    {
                        <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                    }
                    </select>

                </div>
            </div>
        }
        </div>

        <div class="Details content">
            <div class="segmentRow">
                <div class="segmentRowName">Title</div>
                <div class="segmentRowValue"><div style="width:300px; padding:3px; color:Gray; border:1px solid silver; background-color:#E3E3E3;">@Model.Creative.Title</div></div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">Description 1</div>
                <div class="segmentRowValue"><div style="width:300px; padding:3px; color:Gray; border:1px solid silver; background-color:#E3E3E3;">@Model.Creative.Desc1 &nbsp;</div></div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">Description 2</div>
                <div class="segmentRowValue"><div style="width:300px; padding:3px; color:Gray; border:1px solid silver; background-color:#E3E3E3;">@Model.Creative.Desc2 &nbsp;</div></div>
            </div>
        </div>

        <div class="Associations content">
        
            <div style="margin-bottom:10px;">Campaigns/Adgroups:</div>

            @foreach (EdgeBiUI.Models.AssociationRowModel association in Model.Associations)
            {
                <div class="associationRow">
                    <span>@(association.Campaign.Name)</span>
                    >
                    <span>@(association.AdGroup.Name)</span>
                </div>
            }        
        </div>
        
    </div>


    <div id="Buttons">
        <input type="button" value="Apply" onclick="SaveCreative(false);" />
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="SaveCreative(true);" />
    </div>
        
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Creatives/Index.cshtml
@model EdgeBiUI.Models.CreativeListModel
@using Easynet.Edge.UI.Data;
           
@{
    ViewBag.Title = "Creatives";
}

<script type="text/javascript">

    function openCreativeDetails(creativeGK) {
        var creativesGK = "";
        $("#IndexDynamicTableContainer input:checked").each(function () { creativesGK += this.name.split('_')[1] + ","; });

        var containsGK = false;
        $("#IndexDynamicTableContainer input:checked").each(function () { if (this.name.split('_')[1] == creativeGK) containsGK = true; });

        if (containsGK && creativesGK.length > 0)
            openMultipleCreativeDetails();
        else
        {
            $.get('@(Url.Action("EditCreative", "Creatives"))', { creativeGK: creativeGK }, function (data) {
                $('#ControllerDialogDiv').html(data);
                openController(600, 400);
               })
			.fail(window.parent.handleError);
        }
    }

    function openMultipleCreativeDetails() {
        var creativesGK = "";
        $("#IndexDynamicTableContainer input:checked").each(function () { creativesGK += this.name.split('_')[1] + ","; });
        if (creativesGK.length > 0) {
            $.get('@(Url.Action("EditMultipleCreatives", "Creatives"))', { creativesGK: creativesGK }, function (data) {
                $('#ControllerDialogDiv').html(data);
                openController(600, 400);
               })
			.fail(window.parent.handleError);
        }
    }

    function findCreatives() {
        searchText = $("#search_value").val();
        $.get('@(Url.Action("FindCreatives", "Creatives"))', { searchText: searchText }, function (data) {
            $('#IndexDynamicTableContainer').html(data);
            $(".IndexTableRowNoResult").css("display", "block");
           })
			.fail(window.parent.handleError);
    }

</script>

<div class="IndexTopNav">
    @using (Html.BeginForm("FindCreatives", "Creatives", FormMethod.Post, new { id = "FilterForm", defaultbutton = "FilterButton" }))
    {
    <input type="text" name="search_value" class="searchText" id="search_value" />
    <input type="button" value="Find" id="FilterButton" onclick="findCreatives()" />
    }
</div>

<div class="TableActions" style="text-align:left;">
    <a href="" onclick="openMultipleCreativeDetails(); return false;">Edit Multiple</a>
</div>

<div id="IndexDynamicTableContainer">
@Html.Partial("Table", Model)
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Creatives/MultiCreativeDetails.cshtml
@model EdgeBiUI.Models.MutliCreativeModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function editSegmentValue(segID) {
        var d = $("#creativeSegmentValue_" + segID).attr("disabled");
        if (d == true)
            $("#creativeSegmentValue_" + segID).attr("disabled", "");
        else
            $("#creativeSegmentValue_" + segID).attr("disabled", "disabled");
    }

    function SaveCreatives(closeAfter) {
        $.post($('#PageEditorForm').attr("action"), $('#PageEditorForm').serialize(), function (data) {
            if (data == "OK") {
                if (closeAfter)
                    closeControllerDialog();
            } else {
                $('#ControllerDialogDiv').html(data);
            }
              }).error(window.parent.handleError);
    }
</script>

<div id="container">

    <div class="containerTitle">
        (Multiple Creatives)
    </div>
    @using (Html.BeginForm("EditMultipleCreatives", "Creatives", new { creativesGK = Model.CreativesGK }, FormMethod.Post, new { id = "PageEditorForm" }))
    {
    <div id="Tabs">        
        <ul class="menu">
			<li class="active" id="Segments">Segments</li>
		</ul>
    </div>

    <div id="TabsContent">
        
        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select id="creativeSegmentValue_@(seg.SegmentRow.SegmentID)" name="creativeSegmentValue_@(seg.SegmentRow.SegmentID)" disabled="disabled" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-100" @(seg.SelectedValue == -100 ? "selected=\"selected\"" : "")></option>
                        <option value="-1">(none)</option>
						<option value="-1000">Add New...</option>
                    @foreach (Oltp.SegmentValueRow value in seg.Values)
                    {
                        <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                    }
                    </select>
                    <input type="checkbox" name="creativeSegmentValueEdit_@(seg.SegmentRow.SegmentID)" value="1" onclick="editSegmentValue(@(seg.SegmentRow.SegmentID));" />
                </div>
            </div>
        }
        </div>

        
    </div>


    <div id="Buttons">
        <input type="button" value="Apply" onclick="SaveCreatives(false);" />
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="SaveCreatives(true);" />
    </div>
        
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Creatives/Table.cshtml
@model EdgeBiUI.Models.CreativeListModel
@using Easynet.Edge.UI.Data;

<div class="IndexTable">
    <div class="IndexTableHeader">
        <div class="" style="float:left; width:50%; height:14px; overflow:hidden;"><div style="padding-left:30px;">Name</div></div>
        <div class="" style="float:left; width:50%; height:14px; overflow:hidden;">Description</div>
    </div>
    @foreach (Oltp.CreativeRow creative in Model.Creatives)
    {
        <div class="IndexTableRow" id="IndexTableRow_@(creative.GK)" onclick="selectRow(@(creative.GK), false);">
            <div class="IndexTableName">
                <input type="checkbox" name="creativeMultiSelect_@(creative.GK)" style="float:left;" />
                <div style="padding-left:30px;" onclick="openCreativeDetails(@creative.GK)" title="GK=@creative.GK">                    
                    @creative.Title
                </div>
            </div>
            <div class="IndexTableDesc">@(creative.IsDesc1Null() ? "" : EdgeBiUI.Auxilary.Helpers.GetShortDescription(creative.Desc1, 60))</div>
        </div>
    }

    @if (Model.Creatives.Count == 0)
    {
        <div class="IndexTableRowNoResult">No Creatives Found</div>
    }
</div>