moreweb/EdgeBiUI/EdgeBiUI/Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Easynet.Edge.UI.Client;
using Easynet.Edge.UI.Data;
using System.Data;
using EdgeBiUI.Auxilary;

namespace EdgeBiUI.Controllers
{
    public class CampaignsController : Controller
    {
        int acc_id = 0;
        string session_id = null;

        public CampaignsController()
        {
            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;
        }

        public ActionResult Index(int account, string session)
        {
            AppState.AccountID = account;
            AppState.SessionID = session;

            acc_id = AppState.AccountID;
            session_id = AppState.SessionID;

            Models.CampaignListModel m = new Models.CampaignListModel();
            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                Oltp.CampaignDataTable t = client.Service.Campaign_Get(acc_id, null, null, null, false);
                m.Statuses = client.Service.CampaignStatus_Get().ToDictionary(x => x.ID, x => x.Name);
                m.Channels = client.Service.Channel_Get().ToDictionary(h => h.ID, h => h.DisplayName);
                
                foreach(Oltp.CampaignRow c in t)
					m.Campaigns.Add(new Models.CampaignRowModel() {
						CampaignGK = c.GK,
						CampaignName = c.IsNameNull() ? "(no name)" : c.Name,
						Status = m.Statuses.ContainsKey(c.StatusID) ? m.Statuses[c.StatusID] : String.Format("Unknown ({0})", c.StatusID),
						ChannelName = m.Channels.ContainsKey(c.ChannelID) ? m.Channels[c.ChannelID] : String.Format("Unknown ({0})", c.ChannelID)
					});
            }

            return View(m);
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public PartialViewResult Find(FormCollection colls)
        {
            Models.CampaignListModel m = new Models.CampaignListModel();
            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                m.Statuses = client.Service.CampaignStatus_Get().ToDictionary(x => x.ID, x => x.Name);
                m.Channels = client.Service.Channel_Get().ToDictionary(h => h.ID, h => h.DisplayName);
                
                int? channelID = colls["Channel"] == "0" ? null : (int?)int.Parse(colls["Channel"]);
                int? statusID = colls["Status"] == "0" ? null : (int?)int.Parse(colls["Status"]);
                string textToSearch = colls["searchText"].Trim().Equals("") ? null : colls["searchText"].Trim()+"*";
                bool filterByAdgroup = colls["typeOfSearch"] == "adgroup";

                Oltp.CampaignDataTable t = client.Service.Campaign_Get(acc_id, channelID, statusID, textToSearch, filterByAdgroup);
                foreach (Oltp.CampaignRow c in t)
                    m.Campaigns.Add(new Models.CampaignRowModel() { CampaignGK = c.GK, CampaignName = c.Name, Status = m.Statuses[c.StatusID], ChannelName = m.Channels[c.ChannelID] });

                DataTable targets = client.Service.CampaignTargets_Get(acc_id, null);
                Dictionary<long, Models.CampaignRowModel> dic = m.Campaigns.ToDictionary(q => q.CampaignGK, q => q);

                foreach (DataRow r in targets.Rows)
                {
                    long campaignGK = (long)(int)r["CampaignGK"];
                    if (dic.ContainsKey(campaignGK))
                    {
                        dic[campaignGK].CPA1 = r["CPA_new_users"] == DBNull.Value ? null : (double?)r["CPA_new_users"];
                        dic[campaignGK].CPA2 = r["CPA_new_activations"] == DBNull.Value ? null : (double?)r["CPA_new_activations"];
                    }
                }

            }

            return PartialView("Table", m.Campaigns);
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public PartialViewResult GetAdgroupsForCampaign(long campaignGK)
        {
            List<Models.AdgroupRowModel> L = new List<Models.AdgroupRowModel>();
            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                Oltp.AdgroupDataTable t = client.Service.Adgroup_Get(campaignGK, null);

                foreach (Oltp.AdgroupRow a in t)
                    L.Add(new Models.AdgroupRowModel() { AdgroupGK = a.GK, AdgroupName = a.Name });
            }

            return PartialView("TableAdgroups", L);
        }

        [OutputCache(Duration = 0, NoStore = true)]
        public PartialViewResult EditCampaign(long campaignGK)
        {
            Models.CampaignModel m = new Models.CampaignModel();

            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                m.Campaign = client.Service.Campaign_GetSingle(campaignGK)[0];


                Oltp.SegmentDataTable segments = client.Service.Segment_Get(acc_id, true);
                foreach (Oltp.SegmentRow segment in segments)
                {
                    bool is_campaign_segment = ((Auxilary.SegmentAssociationFlags)segment.Association).HasFlag(Auxilary.SegmentAssociationFlags.Campaign);
                    if (is_campaign_segment)
                    {
                        Oltp.SegmentValueDataTable segment_values = client.Service.SegmentValue_Get(acc_id, segment.SegmentID);
                        int value;
                        switch (segment.SegmentID)
                        {
                            case 1: value = m.Campaign.Segment1; break;
                            case 2: value = m.Campaign.Segment2; break;
                            case 3: value = m.Campaign.Segment3; break;
                            case 4: value = m.Campaign.Segment4; break;
                            case 5: value = m.Campaign.Segment5; break;
                            default: value = m.Campaign.Segment1; break;
                        }
                        m.Segments.Add(new Models.SegmentRowModel() { SegmentRow = segment, Values = segment_values.ToList(), SelectedValue = value });
                    }
                }

                DataTable t = client.Service.CampaignTargets_Get(acc_id, campaignGK);
                if (t.Rows.Count > 0)
                {
                    m.Target_Customer = t.Rows[0]["CPA_new_users"] == DBNull.Value ? null : (double?)t.Rows[0]["CPA_new_users"];
                    m.Target_Depositor = t.Rows[0]["CPA_new_activations"] == DBNull.Value ? null : (double?)t.Rows[0]["CPA_new_activations"];
                }
            }


            return PartialView("CampaignDetails", m);

        }

        [HttpPost]
        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult SaveTargets(FormCollection coll)
        {
            using (var client = OltpLogicClient.Open(session_id))
            {
                if (client == null)
                    return PartialView("~/Views/Shared/_SessionExpiredView.cshtml");

                string a1 = coll["campaignsGK"];
                Dictionary<long, long> campaignsGK = a1.Split(',').Select(x => long.Parse(x)).ToDictionary(d=>d, d=>d);
                DataTable targetsTable = client.Service.CampaignTargets_Get(acc_id, null);
                
                List<DataRow> RowsToRemove = new List<DataRow>();
                foreach(DataRow r in targetsTable.Rows)
                {
                    long gk = long.Parse(r["CampaignGK"].ToString());
                    if (!campaignsGK.ContainsKey(gk))
                        RowsToRemove.Add(r);
                }
                RowsToRemove.ForEach(x => targetsTable.Rows.Remove(x));

                List<DataRow> RowsToAdd = new List<DataRow>();
                foreach (long gk in campaignsGK.Keys)
                {
                    bool f = false;
                    foreach (DataRow r in targetsTable.Rows)
                        if (long.Parse(r["CampaignGK"].ToString()) == gk)
                            f = true;

                    if (!f)
                    {
                        DataRow r = targetsTable.NewRow();
                        r["CampaignGK"] = gk;
                        r["AdgroupGK"] = -1;
                        RowsToAdd.Add(r);
                    }
                }

                RowsToAdd.ForEach(x => targetsTable.Rows.Add(x));

                foreach (DataRow r in targetsTable.Rows)
                {
                    long gk = long.Parse(r["CampaignGK"].ToString());
                    double? target1, target2;

                    if (coll["campaigntarget_" + gk + "_CPA1"].Equals(""))
                        target1 = null;
                    else
                        target1 = double.Parse(coll["campaigntarget_" + gk + "_CPA1"]);

                    if (coll["campaigntarget_" + gk + "_CPA2"].Equals(""))
                        target2 = null;
                    else
                        target2 = double.Parse(coll["campaigntarget_" + gk + "_CPA2"]);

                    if (target1 == null)
                        r["CPA_new_users"] = DBNull.Value;
                    else
                        r["CPA_new_users"] = target1;

                    if (target2 == null)
                        r["CPA_new_activations"] = DBNull.Value;
                    else
                        r["CPA_new_activations"] = target2;

moreweb/EdgeBiUI/EdgeBiUI/Views/Campaigns/AdgroupDetails.cshtml
@model EdgeBiUI.Models.AdgroupModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function SaveAdgroup(closeAfter) {
        $.post($('#AdgroupEditForm').attr("action"), $('#AdgroupEditForm').serialize(), function (data) {
            if (data == "OK") {
                if (closeAfter)
                    closeControllerDialog();
            } else {
                $('#ControllerDialogDiv').html(data);
            } 
        }).error(window.parent.handleError);
    }
</script>

<div id="container">

    <div class="containerTitle">
       @Model.Adgroup.Name
    </div>
    @using (Html.BeginForm("EditAdgroup", "Campaigns", new { adgroupGK = Model.Adgroup.GK }, FormMethod.Post, new { id = "AdgroupEditForm" }))
    {
    <div id="Tabs">        
        <ul class="menu">						
            <li class="active" id="Segments">Segments</li>
            <li class="ControllerTabsLi" id="Keywords">Keywords</li>
            <li class="ControllerTabsLi" id="Creatives">Creatives</li>
		</ul>
    </div>

    <div id="TabsContent">
        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select name="adgroupSegmentValue_@(seg.SegmentRow.SegmentID)" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-1">(none)</option>
						<option value="-1000">Add New...</option>
                        @foreach (Oltp.SegmentValueRow value in seg.Values)
                        {
                        <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                        }
                    </select>
                </div>
            </div>
        }
        </div>        
        
        <div class="Keywords content">
            <div class="adgroupInnerTable">
                <div class="adgroupInnerTableHeader">
                    <div style="float:left; width:40%; height:14px; overflow:hidden;">
                        Keyword
                    </div>
                    <div style="float:left; width:20%; height:14px; overflow:hidden;">
                        Match Type
                    </div>
                    <div style="float:left; width:40%; height:14px; overflow:hidden;">
                        Destination URL
                    </div>
                </div>
            
                @foreach (EdgeBiUI.Models.AdgroupKeywordModel keyword in Model.Keywords)
                {
                    <div class="adgroupInnerTableRow">
                        <div style="float:left; width:40%; height:14px; overflow:hidden;">
                            @keyword.KeywordName
                        </div>
                        <div style="float:left; width:20%; height:14px; overflow:hidden;">
                            @keyword.MatchType
                        </div>
                        <div style="float:left; width:40%; height:14px; overflow:hidden;">
                            @keyword.DestinationURL
                        </div>
                    </div>
                }
            </div>
            
        </div>

        <div class="Creatives content">
            <div class="adgroupInnerTable">
                <div class="adgroupInnerTableHeader">
                    <div style="float:left; width:50%;">
                        Creative
                    </div>
                    <div style="float:left; width:50%;">
                        Segment
                    </div>
                </div>
            
                @foreach (EdgeBiUI.Models.AdgroupCreativeModel creative in Model.Creatives)
                {
                    <div class="adgroupInnerTableRow">
                        <div style="float:left; width:50%; overflow:hidden;">
                            <div style="font-weight:bold; margin-bottom:8px;">
                                @creative.Title
                            </div>
                            <div style="">
                                @creative.Desc1
                            </div>
                            <div style="margin-bottom:8px;">
                                @creative.Desc2
                            </div>
                            <div style="margin-bottom:8px;" title="@creative.DestinationURL">
                                @creative.DisplayURL
                            </div>
                            <div class="adgroupCreativeDestURL" title="@creative.DestinationURL">
                                @creative.DestinationURL
                            </div>
                        </div>
                        <div style="float:left; width:50%; overflow:hidden;">
                            <div style="padding-top:25px;">
                                @foreach (EdgeBiUI.Models.SegmentRowModel seg in creative.Segments)
                                {
                                    <div class="segmentRow">
                                        <div class="segmentRowName" style="width:90px;">@seg.SegmentRow.Name</div>
                                        <div class="segmentRowValue" style="margin-left:95px;">
                                            <select name="adgroupcreative@(creative.AdgroupCreativeGK)_SegmentValue_@(seg.SegmentRow.SegmentID)" style="width:100px;" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                                                <option value="-1">(none)</option>
												<option value="-1000">Add New...</option>
                                                @foreach (Oltp.SegmentValueRow value in seg.Values)
                                                {
                                                <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>


    <div id="Buttons">
        <input type="button" value="Apply" onclick="SaveAdgroup(false);" />
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="SaveAdgroup(true);" />
    </div>
        
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Campaigns/CampaignDetails.cshtml
@model EdgeBiUI.Models.CampaignModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function SaveCampaign(closeAfter) {
        if ($("#container .errorValue").length > 0) {
            window.parent.handleError({ message: "Invalid target value." });
            //alert("wrong target value");
            return;
        }

        $.post($('#CampaignEditForm').attr("action"), $('#CampaignEditForm').serialize(), function (data) {
            var cpa1 = $("#TabsContent input[name=Target1]").val();
            var cpa2 = $("#TabsContent input[name=Target2]").val();
            $("input[name=campaigntarget_@(Model.Campaign.GK)_CPA1]").val(cpa1);
            $("input[name=campaigntarget_@(Model.Campaign.GK)_CPA2]").val(cpa2);
            if (data == "OK") {
                if (closeAfter)
                    closeControllerDialog();
            } else {
                $('#ControllerDialogDiv').html(data);
            } 
        }).error(window.parent.handleError);
    }
</script>

<div id="container">

    <div class="containerTitle">
       @Model.Campaign.Name
    </div>
    @using (Html.BeginForm("EditCampaign", "Campaigns", new { campaignGK = Model.Campaign.GK }, FormMethod.Post, new { id = "CampaignEditForm" }))
    {
    <div id="Tabs">        
        <ul class="menu">						
            <li class="active" id="Segments">Segments</li>
            <li class="ControllerTabsLi" id="Targets">Targets</li>
		</ul>
    </div>

    <div id="TabsContent">
        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select name="campaignSegmentValue_@(seg.SegmentRow.SegmentID)" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-1">(none)</option>
						<option value="-1000">Add New...</option>
                    @foreach (Oltp.SegmentValueRow value in seg.Values)
                    {
                        <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                    }
                    </select>
                </div>
            </div>
        }
        </div>        
        
        <div class="Targets content">
            <div class="segmentRow">
                <div class="segmentRowName">CPA (Customers)</div>
                <div class="segmentRowValue">
                    <input type="text" onkeyup="checkvalue(this)" name="Target1" value="@Model.Target_Customer" />
                </div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">CPA (Depositors)</div>
                <div class="segmentRowValue">
                    <input type="text" onkeyup="checkvalue(this)" name="Target2" value="@Model.Target_Depositor" />
                </div>
            </div>
            
        </div>
    </div>


    <div id="Buttons">
        <input type="button" value="Apply" onclick="SaveCampaign(false);" />
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="SaveCampaign(true);" />
    </div>
        
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Campaigns/MultiCampaignDetails.cshtml
@model EdgeBiUI.Models.MultiCampaignModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function SaveCampaigns(closeAfter) {
        if ($("#container .errorValue").length > 0) {
            window.parent.handleError({ message: "Invalid target values." });
            //alert("wrong target value");
            return;
        }

        $.post($('#CampaignEditForm').attr("action"), $('#CampaignEditForm').serialize(), function (data) {
            if (closeAfter)
                closeControllerDialog();
           }).error(window.parent.handleError);
    }

    function editSegmentValue(segID) {
        var d = $("#campaignSegmentValue_" + segID).attr("disabled");
        if (d == true)
            $("#campaignSegmentValue_" + segID).attr("disabled", "");
        else
            $("#campaignSegmentValue_" + segID).attr("disabled", "disabled");
    }

    function editTarget(targetID) {
        var d = $("#Target" + targetID).attr("disabled");
        if (d == true)
            $("#Target" + targetID).attr("disabled", "");
        else
            $("#Target" + targetID).attr("disabled", "disabled");
    }
</script>

<div id="container">

    <div class="containerTitle">
       (multiple campaigns)
    </div>
    @using (Html.BeginForm("EditMultipleCampaign", "Campaigns", new { campaignsGK = Model.CampaignsGK }, FormMethod.Post, new { id = "CampaignEditForm" }))
    {
        
    <div id="Tabs">        
        <ul class="menu">						
            <li class="active" id="Segments">Segments</li>
            <li class="ControllerTabsLi" id="Targets">Targets</li>
		</ul>
    </div>

    <div id="TabsContent">
        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select id="campaignSegmentValue_@(seg.SegmentRow.SegmentID)" name="campaignSegmentValue_@(seg.SegmentRow.SegmentID)" disabled="disabled" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-100" @(seg.SelectedValue == -100 ? "selected=\"selected\"" : "")></option>
                        <option value="-1">(none)</option>
						<option value="-1000">Add New...</option>
                    @foreach (Oltp.SegmentValueRow value in seg.Values)
                    {
                        <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                    }
                    </select>
                    <input type="checkbox" name="campaignSegmentValueEdit_@(seg.SegmentRow.SegmentID)" value="1" onclick="editSegmentValue(@(seg.SegmentRow.SegmentID));" />
                </div>
            </div>
        }
        </div>        
        
        <div class="Targets content">
            <div class="segmentRow">
                <div class="segmentRowName">CPA (Customers)</div>
                <div class="segmentRowValue">
                    <input type="text" id="Target1" name="Target1" value="@Model.Target_Customer" disabled="disabled" onkeyup="checkvalue(this)" />
                    <input type="checkbox" name="EditTarget1" value="1" onclick="editTarget(1);" />
                </div>
            </div>
            <div class="segmentRow">
                <div class="segmentRowName">CPA (Depositors)</div>
                <div class="segmentRowValue">
                    <input type="text" id="Target2" name="Target2" value="@Model.Target_Depositor" disabled="disabled" onkeyup="checkvalue(this)" />
                    <input type="checkbox" name="EditTarget2" value="1" onclick="editTarget(2);" />
                </div>
            </div>
            
        </div>
    </div>


    <div id="Buttons">
        <input type="button" value="Apply" onclick="SaveCampaigns(false);" />
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="SaveCampaigns(true);" />
    </div>
        
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Campaigns/MultipleAdgroupDetails.cshtml
@model EdgeBiUI.Models.MultipleAdgroupModel
@using Easynet.Edge.UI.Data;

<script type="text/javascript">
    $(function () {
        OpenTabsJS();
    });

    function SaveAdgroups(closeAfter) {
        $.post($('#AdgroupEditForm').attr("action"), $('#AdgroupEditForm').serialize(), function (data) {
            if (closeAfter)
                closeControllerDialog();
           }).error(window.parent.handleError);
    }

    function editSegmentValue(segID) {
        var d = $("#adgroupSegmentValue_" + segID).attr("disabled");
        if (d == true)
            $("#adgroupSegmentValue_" + segID).attr("disabled", "");
        else
            $("#adgroupSegmentValue_" + segID).attr("disabled", "disabled");
    }

</script>

<div id="container">

    <div class="containerTitle">
       (multiple adgroups)
    </div>
    @using (Html.BeginForm("EditMultipleAdgroups", "Campaigns", new { adgroupsGK = Model.AdgroupsGK }, FormMethod.Post, new { id = "AdgroupEditForm" }))
    {
    <div id="Tabs">        
        <ul class="menu">						
            <li class="active" id="Segments">Segments</li>
		</ul>
    </div>

    <div id="TabsContent">
        <div class="Segments content">
        @foreach (EdgeBiUI.Models.SegmentRowModel seg in Model.Segments)
        {
            <div class="segmentRow">
                <div class="segmentRowName">@seg.SegmentRow.Name</div>
                <div class="segmentRowValue">
                    <select id="adgroupSegmentValue_@(seg.SegmentRow.SegmentID)" name="adgroupSegmentValue_@(seg.SegmentRow.SegmentID)" disabled="disabled" onchange="handleNewValue(this)" segmentID="@(seg.SegmentRow.SegmentID)" originalValue="@(seg.SelectedValue)">
                        <option value="-100" @(seg.SelectedValue == -100 ? "selected=\"selected\"" : "")></option>
                        <option value="-1">(none)</option>
						<option value="-1000">Add New...</option>
                        @foreach (Oltp.SegmentValueRow value in seg.Values)
                        {
                        <option value="@(value.ValueID)" @(seg.SelectedValue == value.ValueID ? "selected=\"selected\"" : "")>@(value.Value)</option>
                        }
                    </select>
                    <input type="checkbox" name="adgroupSegmentValueEdit_@(seg.SegmentRow.SegmentID)" value="1" onclick="editSegmentValue(@(seg.SegmentRow.SegmentID));" />
                </div>
            </div>
        }
        </div>        
    </div>


    <div id="Buttons">
        <input type="button" value="Apply" onclick="SaveAdgroups(false);" />
        <input type="button" value="Cancel" onclick="closeControllerDialog();" />        
        <input type="button" value="OK" onclick="SaveAdgroups(true);" />
    </div>
        
    }
</div>

moreweb/EdgeBiUI/EdgeBiUI/Views/Campaigns/Table.cshtml
@model List<EdgeBiUI.Models.CampaignRowModel>
@using Easynet.Edge.UI.Data;

<div id="CampaignsIndexTable" class="IndexTable">
    <div class="IndexTableHeader">
        <div class="" style="float:left; width:60%; height:14px; overflow:hidden;"><div style="margin-left:73px;">Name</div></div>
        <div class="" style="float:left; width:10%; height:14px; overflow:hidden;">Channel</div>
        <div class="" style="float:left; width:10%; height:14px; overflow:hidden;">Status</div>
        <div class="IndexTableDescCPA" style="float:left; width:10%; height:14px; font-size:13px; letter-spacing:-1px; overflow:hidden; display:none;">CPA (Customers)</div>
        <div class="IndexTableDescCPA" style="float:left; width:10%; height:14px; font-size:13px; letter-spacing:-1px; overflow:hidden; display:none;">CPA (Depositors)</div>
    </div>
    @using (Html.BeginForm("SaveTargets", "Campaigns", FormMethod.Post, new { id = "TargetsEditorForm", defaultbutton = "FilterButton222" }))
    {
        foreach (EdgeBiUI.Models.CampaignRowModel campaign in Model)
        {
            <div class="IndexTableRow" id="IndexTableRow_@(campaign.CampaignGK)" onclick="selectRow(@(campaign.CampaignGK), false);">
                <div class="IndexTableName" style="width:60%;">
                    <div class="campaignMultiSelect"><input type="checkbox" name="campaignMultiSelect_@(campaign.CampaignGK)" /></div>
                    <div class="campaignButtonClose" onclick="openAdGroups(@campaign.CampaignGK); changeIcon(this);"></div>
                    <div style="float:left; margin-left:5px; margin-top:2px;" onclick="openCampaignDetails(@campaign.CampaignGK)" title="GK=@campaign.CampaignGK">@campaign.CampaignName</div>
                </div>
                <div class="IndexTableDesc" style="width:10%;">@campaign.ChannelName</div>
                <div class="IndexTableDesc" style="width:10%;">@campaign.Status</div>
                <div class="IndexTableDesc IndexTableDescCPA" style="width:10%; display:none;">
                    <input name="campaigntarget_@(campaign.CampaignGK)_CPA1" type="text" value="@(campaign.CPA1)" style="width:70px; margin-right:5px; height:20px; direction:ltr; text-align:left;" onkeyup="checkvalue(this)" onchange="cpa_has_changed=true;" originalValue="@(campaign.CPA1)" />
                </div>
                <div class="IndexTableDesc IndexTableDescCPA" style="width:10%; display:none;">
                    <input name="campaigntarget_@(campaign.CampaignGK)_CPA2" type="text" value="@(campaign.CPA2)" style="width:70px; height:20px; direction:ltr; text-align:left;" onkeyup="checkvalue(this)" onchange="cpa_has_changed=true;" originalValue="@(campaign.CPA2)" />
                </div>
                <input type="hidden" name="campaignsGK" value="@(campaign.CampaignGK)" />
            </div>
            <div class="IndexTableContainer" id="@("Adgroups" + campaign.CampaignGK)" style="display:none;">
            
            </div>
        }
    }
    @if (Model.Count == 0)
    {
        <div class="IndexTableRowNoResult">No Campaigns Found</div>
    }
</div>